### ISSUE TITLE
Add empty grid to dashboard

### ISSUE THREAD

**Issue by cynthiablack** [HattieTavares/mood-colors#14]
1. Create empty grid for current-week checkins
2. Convert numerical values in CheckIns collections to colors
3. Create empty grid for subsequent weeks

**Comment by cynthiablack** [comment]
1 & 3 complete.
Working on function for 2.

**Comment by emmebravo** [comment]
@cynthiablack are you making more than one PR per issue? did you push a PR for task 1 & 3?

**Comment by cynthiablack** [comment]
@emmebravo I pushed a PR for 1 & 3. Since it appears Item 2 is resolved, as well, I'll close this issue.
