### ISSUE TITLE
ADD POST route for checkin

### ISSUE THREAD

**Issue by fakehouseplant** [HattieTavares/mood-colors#22]
A post request for new checkin needs to be added to checkin.js in the routes folder

**Comment by emmebravo** [comment]
this is gonna be a `PUT` not a `POST`, we have to do some research first

**Comment by fakehouseplant** [comment]
Isn't it a post request? We're creating the check in when we fill out the form.

**Comment by fakehouseplant** [comment]
Oh, is this related to the idea that a new document would be created each day regardless if a user checks in or not? I think we should still build it as a post request for now, for mvp purposes, and we can change it to a put request later, if we can figure out how to automatically create a document each day for each user.

**Comment by HattieTavares** [comment]
It's gonna change to a PUT if/when we figure out the function trigger right right? For now I think we should just make it a POST to have that part working and change it later.

**Comment by emmebravo** [comment]
No, we want to create the squares automatically at midnight, so the people would be making a `PUT` request to update their mood. It's just in case they don't put their mood one day, so the square still exists.

**Comment by HattieTavares** [comment]
@emmebravo Yea that's the goal, it just may not be working in time for the MVP, figure it's better to just have the stuff working this way first?

**Comment by HattieTavares** [comment]
Done
