### ISSUE TITLE
Dashboard -- Add display of data on click 

### ISSUE THREAD

**Issue by fakehouseplant** [HattieTavares/mood-colors#51]
On the dashboard view, clicking a completed square should display the rest of the data on a pop up card. See figma file for design.

**Comment by emmebravo** [comment]
it works on hover, not on click... click as an optimization?

**Comment by HattieTavares** [comment]
@emmebravo we originally chose click because it would work better on mobile, but then I discovered that the tooltip automatically reverts to clicking on mobile so I didn't bother complicating it, so it hovers on desktop and click on mobile.
